language: python
python:
  - 2.7
  - 3.5
  - 3.6
env:
  - FLASK_VERSION=0.9
  - FLASK_VERSION=0.10
  - FLASK_VERSION=0.11
  - FLASK_VERSION=0.12
matrix:
  exclude:
    - python: 3.5
      env: FLASK_VERSION=0.9
    - python: 3.6
      env: FLASK_VERSION=0.9
install:
  - pip install -r requirements.txt
  - pip install -I Flask==$FLASK_VERSION
script:
  - py.test test_flask_redislite.py --pep8 flask_redislite.py -v --cov=flask_redislite --cov-report term-missing
